"""initial

Revision ID: 43aaf1e25a4b
Revises: 003
Create Date: 2026-02-28 22:43:08.297217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43aaf1e25a4b'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bank_accounts_account_id', table_name='bank_accounts')
    op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=False)
    op.drop_index('ix_plaid_items_item_id', table_name='plaid_items')
    op.create_index(op.f('ix_plaid_items_id'), 'plaid_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plaid_items_id'), table_name='plaid_items')
    op.create_index('ix_plaid_items_item_id', 'plaid_items', ['item_id'], unique=1)
    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.create_index('ix_bank_accounts_account_id', 'bank_accounts', ['account_id'], unique=1)
    # ### end Alembic commands ###
